// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapiASP.Models;

#nullable disable

namespace webapiASP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241201123207_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapiASP.Models.Prices", b =>
                {
                    b.Property<long>("PricesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PricesId"));

                    b.Property<long>("ProductCode")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("PricesId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("webapiASP.Models.RegistrationProduct", b =>
                {
                    b.Property<long>("RegistrationProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegistrationProductId"));

                    b.Property<string>("BuilderLastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("PricesId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductCode")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RegistrationProductId");

                    b.HasIndex("PricesId");

                    b.ToTable("RegistrationProduct");
                });

            modelBuilder.Entity("webapiASP.Models.RegistrationProduct", b =>
                {
                    b.HasOne("webapiASP.Models.Prices", "Prices")
                        .WithMany("RegistrationProducts")
                        .HasForeignKey("PricesId");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("webapiASP.Models.Prices", b =>
                {
                    b.Navigation("RegistrationProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
